CREATE TABLE IF NOT EXISTS emprunts_emballages (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    source_type ENUM('client', 'externe') NOT NULL DEFAULT 'client',
    client_id INT UNSIGNED NULL,
    source_nom VARCHAR(150) NULL,
    source_contact VARCHAR(100) NULL,
    produit_id INT UNSIGNED NOT NULL,
    quantite_empruntee INT NOT NULL DEFAULT 0,
    quantite_utilisee INT NOT NULL DEFAULT 0,
    quantite_retournee INT NOT NULL DEFAULT 0,
    emplacement_id INT UNSIGNED NOT NULL,
    date_emprunt DATE NOT NULL,
    statut ENUM('en_cours', 'solde', 'annule') NOT NULL DEFAULT 'en_cours',
    notes TEXT NULL,
    created_by INT UNSIGNED NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_emprunts_client_produit (client_id, produit_id, statut),
    FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE SET NULL,
    FOREIGN KEY (produit_id) REFERENCES produits(id) ON DELETE CASCADE,
    FOREIGN KEY (emplacement_id) REFERENCES emplacements(id) ON DELETE CASCADE,
    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
